// This file is automatically generated
// IMPORT: DO NOT REMOVE

// XXX: Here, we can automatically generate this file based on the
// actions inside this directory.
import categories from "./categories";
const actions = {
	categories();
  // ACTION
};

export default actions;
